# Generated by Django 3.2.3 on 2021-10-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Computer and Electronics', 'Computer and Electronics'), ('Phones and Tablets', 'Phones and Tablets'), ('Fashions and Styles', 'Fashions and Styles'), ('Home and Kitchen', 'Home and Kitchen'), ('Drinks and Wine', 'Drinks and Wine'), ('Kids and Toys', 'Kids and Toys'), ('Others', 'Others')], default='Phones and Tablets', max_length=200)),
                ('label', models.CharField(choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY'), ('danger', 'DANGER')], default='primary', max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(default='default.jpg')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ViewedProducts',
            },
        ),
        migrations.CreateModel(
            name='TemporaryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('USA', 'USA'), ('Ghana', 'Ghana')], max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('telephone', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Temporary Address',
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Computer and Electronics', 'Computer and Electronics'), ('Phones and Tablets', 'Phones and Tablets'), ('Fashions and Styles', 'Fashions and Styles'), ('Home and Kitchen', 'Home and Kitchen'), ('Drinks and Wine', 'Drinks and Wine'), ('Kids and Toys', 'Kids and Toys'), ('Others', 'Others')], default='Phones and Tablets', max_length=200)),
                ('label', models.CharField(choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY'), ('danger', 'DANGER')], default='primary', max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(default='default.jpg')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SavedProducts',
            },
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(default='default.jpg')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=True)),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiving_address', models.TextField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchased',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Computer and Electronics', 'Computer and Electronics'), ('Phones and Tablets', 'Phones and Tablets'), ('Fashions and Styles', 'Fashions and Styles'), ('Home and Kitchen', 'Home and Kitchen'), ('Drinks and Wine', 'Drinks and Wine'), ('Kids and Toys', 'Kids and Toys'), ('Others', 'Others')], default='Phones and Tablets', max_length=200)),
                ('label', models.CharField(choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY'), ('danger', 'DANGER')], default='primary', max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(default='default.jpg')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('save_this_product', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('USA', 'USA'), ('Ghana', 'Ghana')], max_length=400)),
                ('zip', models.CharField(max_length=200)),
                ('telephone', models.CharField(default='', max_length=200)),
                ('save_information', models.BooleanField(default=False, max_length=200)),
                ('payment_option', models.CharField(choices=[('Stripe', 'Stripe'), ('Cash', 'Cash')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='product.Menu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
